### ISSUE TITLE
How to create custom asset?

### ISSUE THREAD

**Issue by aplatyps** [princeton-vl/infinigen#75] opened 2023-06-30 03:18 UTC
Is there a template to create custom assets using specified materials and parts? For example, to create a Lionfish Factory.

**Comment by araistrick** [comment] 2023-06-30 03:33
Hello! Your best bet to create an entirely new type of asset is to implement it using blender geometry/shader nodes, then use our worldgen/nodes/transpiler/dev_script.py to convert it to Python code like you see in the codebase. Alternatively, you could start out by just modifying the existing worldgen/assets/creatures/genomes/fish.py and creating a custom version, or replacing its material with a duplicate of worldgen/surfaces/templates/fish body.py that you have modified to look like a lionfish.

We are _very_ excited to get as many people as possible making their own assets and ideally contributing them back into the repo as code. Some minimal tutorials on this will come soon (with at least a roadmap for these tutorials posted tommorow), but polishing everything up to make it seamless and easy to contribute will take some time. For now, the best bet is to experiment around with the existing code sew what you can make. 

Thanks!

**Comment by aplatyps** [comment] 2023-06-30 03:40
Thank for the prompt response! Will there also be a tutorial on how to generate mythical assets or strange animals that does not usually follows the logic of a typical animal? For example, unicorns with wings and platypus

**Comment by araistrick** [comment] 2023-06-30 03:53
There's actually already some code to do something like this somewhere but I think it got cut from the release as the results weren't quite satisfactory and I didn't have time to polish it for release. You can see what the results were like in the compositional creatures figure in the supplement of our paper.

I will try to polish this and/or create a tutorial when I have time but it may be a ways down the list. Please follow up to prod me. For now, doing this type of fantasy creature should be pretty tractable by just modifying the Python, eg if you copy the part of herbivore.py that .attach() on the horns, and do that to a fish instead, it should just get you a fish with horns, or anything like that.

**Closed** 2023-06-30 06:20 UTC

**Comment by codejoker-c** [comment] 2023-06-30 06:29
Since you mentioned that it is possible to create a new custom asset using Blender's geometry and shader nodes with dev_script.py, I'm wondering if there are specific properties in the configuration that can be modified to allow infinigen to generate a scene entirely using Blender nodes. In this way, the entire scene can be converted to python script with dev_script.py and converted back freely.

Thanks!

**Comment by aplatyps** [comment] 2023-06-30 08:54
My attempt to make a platypus using the carnivore and bird class (looks nothing like the actual animal). Hopefully the documentation will cover how to scale, position and rotate someday.

![image_000](https://github.com/princeton-vl/infinigen/assets/103926799/6eda2eda-3d2d-4591-a6fb-1d9669d737c3)

**Comment by araistrick** [comment] 2023-06-30 09:01
> Since you mentioned that it is possible to create a new custom asset using Blender's geometry and shader nodes with dev_script.py, I'm wondering if there are specific properties in the configuration that can be modified to allow infinigen to generate a scene entirely using Blender nodes. In this way, the entire scene can be converted to python script with dev_script.py and converted back freely.
> 
> Thanks!

Good question, I've wondered this a lot too. Creating a scene entirely in blender nodes is possible, but a little restrictive, since nodes don't yet support all the features you might want, and some things are harder to do in geonodes (eg they don't have proper for loops!). 

Geonodes also don't work as well as a software engineering platform, even when converted to Python code, as you're prevented from using other Python libraries or anything non geonodes, it's very all or nothing.

In general, just because something can be done in geonodes does not mean it will be easy, as geonodes are very expressive and most things are technically possible

**Comment by araistrick** [comment] 2023-06-30 09:03
> My attempt to make a platypus using the carnivore and bird class (looks nothing like the actual animal). Hopefully the documentation will cover how to scale, position and rotate someday.
> 
> ![image_000](https://github.com/princeton-vl/infinigen/assets/103926799/6eda2eda-3d2d-4591-a6fb-1d9669d737c3)
> 

Nice! Rotating can be done by changing the ruler angles in the Joint(rest=...) part of attach. Positining happens with the coord= part of attach but the meaning of the variables unfortunately takes some explaining. I think I left a readme in the creatures folder? Might have been stripped for release. If it's not there I will write a new one to explain this soon as it's a little nuanced
